### ISSUE TITLE
Issue with Rain Days

### ISSUE THREAD

**Issue by Pogs2004** [tkeffer/weewx-xaggs#3]
Hi, I am trying to use your xaggs extension to display the number of days with rain (>0.2mm) in the week, month and year pages in my Neowx-Material skin running on WeeWX 4.8. I have installed the extension correctly, however it is not displaying the aggregate days with rain, only a 0. I maybe don't have the argument formatted correctly?

The code I am using is:

```
        <div class="row">
          <div class="col-3 text-muted font-small">
          $week.rain.avg_ge((0.2, 'mm', 'group_rain')) <br>
          Days with Rain
          </div>
          <div class="col-6">
            <h4 class="h2-responsive">$week.rain.sum</h4>
          </div>
          <div class="col-3 text-muted font-small hi-text">
            $week.rainRate.max <br>
            ($week.rainRate.maxtime.format($Extras.Formatting.datetime))
          </div>
        </div>
```

WeeWX is running Debian GNU/Linux 11 (bullseye) on a Raspberry Pi 4B 4GB, installed via DEB package.

You can see the week page here: https://www.360shetland.co.uk/weather/week.html

**Comment by tkeffer** [comment]
The problem is likely that `avg_ge()` is not what you think it is. It's the number of days where the average value of `rain` is greater than 0.2mm. Remember: `rain` is the amount of rain that fell in an archive interval, which is generally only about 5 minutes. It's a rare day where the average value is 0.2mm. That would take 50+ mm of rain for the day.

If what you want is the number of days with more than 0.2mm of rain, that would be `$week.rain.sum_ge((0.2, 'mm', 'group_rain'))`.

Or, perhaps you're looking for something else?

**Comment by Pogs2004** [comment]
> The problem is likely that `avg_ge()` is not what you think it is. It's the number of days where the average value of `rain` is greater than 0.2mm. Remember: `rain` is the amount of rain that fell in an archive interval, which is generally only about 5 minutes. It's a rare day where the average value is 0.2mm. That would take 50+ mm of rain for the day.
> 
> If what you want is the number of days with more than 0.2mm of rain, that would be `$week.rain.sum_ge((0.2, 'mm', 'group_rain'))`.
> 
> Or, perhaps you're looking for something else?

That's sorted it, many thanks! I didn't realise that avg_ge was the average of each archive interval which would be a lot of rain as you say!

**Comment by tkeffer** [comment]
`avg_ge()` is really intended for extensive quantities, such as temperature. For example, the number of days with an average temperature greater than 20ºC.
